"""
Django settings for pawnshop project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = r'***REMOVED***'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'bits-pilani.store',
    'www.bits-pilani.store',
    'admin.bits-pilani.store',
    "127.0.0.1",
    "localhost",
    "api.amazoff.shop",
    "api.bits-pilani.store",
    "amdin.bits-pilani.store",
    "www.api.amazoff.shop",
    "www.api.bits-pilani.store",
    "admin.amazoff.shop",
    "3.108.113.123",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'bits',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'social_django',
    'pwa',
    'django_ses',
    'corsheaders',
    'django_celery_beat'
]
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['email', 'profile'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'bits.middleware.DomainBasedCSRFMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bits.log_middleware.RequestLoggingMiddleware',
    'bits.middleware.BlockUnauthorizedOriginsMiddleware',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'pawnshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pawnshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 2
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '***REMOVED***'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '***REMOVED***'
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID')
if not GOOGLE_OAUTH_CLIENT_ID:
    raise ValueError(
        'GOOGLE_OAUTH_CLIENT_ID is missing.'
        'Have you put it in a file at core/.env ?'
    )

SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

PWA_APP_NAME = 'Bits Pilani Store'
PWA_APP_SHORT_NAME = 'Bits Store'
PWA_APP_DESCRIPTION = 'A BITS Market place, made by BITSians, for BITSians!'
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#000000'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_START_URL = '/'
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en'

PWA_SERVICE_WORKER_PATH = BASE_DIR / 'serviceworker.js'

PWA_APP_ICONS = [
    {"src": "/static/images/icon_144.png", "sizes": "144x144", "type": "image/png"},
    {"src": "/static/images/icon_192.png", "sizes": "192x192", "type": "image/png"},
    {"src": "/static/images/icon_512.png", "sizes": "512x512", "type": "image/png"},
]

PWA_APP_ICONS_APPLE = [
    {"src": "/static/images/icon_512.png", "sizes": "512x512", "type": "image/png"},
]

# Optional: These are okay to keep if you want them shown in Chrome's install screen
PWA_APP_SCREENSHOTS = [
    {"src": "/static/images/icon_512.png", "sizes": "512x512", "form_factor": "wide"},
    {"src": "/static/images/icon_512.png", "sizes": "512x512"},
]

# Optional: If you plan to add shortcuts later
PWA_APP_SHORTCUTS = []


PWA_APP_DEBUG_MODE = DEBUG

MEDIA_ROOT = BASE_DIR/'media'
MEDIA_URL = '/media/'
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

import os
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'request_logs.log'),
        },
    },
    'loggers': {
        'bits': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'contact@example.com'
# EMAIL_HOST_PASSWORD = '***REMOVED***'

EMAIL_BACKEND = 'django_ses.SESBackend'
AWS_ACCESS_KEY_ID  = '***REMOVED***'
AWS_SECRET_ACCESS_KEY = '***REMOVED***'
AWS_SES_REGION_NAME = 'ap-south-1'
AWS_SES_REGION_ENDPOINT = 'email.ap-south-1.amazonaws.com'
# Add these CORS settings to your settings.py
# Remove the duplicate CORS_ALLOWED_ORIGINS near the top
# Keep only these CORS settings at the bottom:


# CORS Configuration


CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'method',
    'user-agent',
    'x-***REMOVED***',
    'x-requested-with',
]

CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = [
    "https://bits-pilani.store",
    "https://www.bits-pilani.store",
    "http://127.0.0.1:8000",
    "https://amazoff.shop",
    "http://localhost:5173",
    "https://pawnshop-react-frontend.s3.ap-south-1.amazonaws.com",
]

CSRF_COOKIE_DOMAIN = ".bits-pilani.store"
SESSION_COOKIE_DOMAIN = ".bits-pilani.store"
CSRF_COOKIE_NAME = '***REMOVED***'
CSRF_COOKIE_AGE = 60 * 60 * 24 * 7 * 52
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_PATH = '/'
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_USE_SESSIONS = False
CSRF_HEADER_NAME = '***REMOVED***'

SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'None'

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "https://pawnshop-react-frontend.s3.ap-south-1.amazonaws.com",
    "https://amazoff.shop",
    "https://bits-pilani.store",
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': None,
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
        }
    }
}

CSRF_FAILURE_VIEW = 'bits.views.csrf_failure_debug'

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'mark-items-sold-daily': {
        'task': 'bits.tasks.mark_old_items_as_sold',
        'schedule': crontab(hour=9, minute=11),
    },
}
