from django.urls import path
from . import views

urlpatterns = [
    path('auth-receiver', views.auth_receiver, name='auth_receiver'),
    path("", views.home, name = "home"),
    path("sign-in", views.sign_in, name='sign_in'),
    path("sign-out", views.sign_out, name='sign_out'),
    path("add-product", views.add_product, name='add_product'),
    path("item/<int:id>", views.item_detail, name='item_detail'),
    path('my-listings/', views.my_listings, name='my_listings'),
    path("delete-item/<int:id>/", views.delete_item, name='delete_item'),
    path("edit-item/<int:id>", views.edit_item, name="edit_item"),
    path("feedback", views.feedback, name='feedback'),
    path("marksold/<int:id>", views.marksold, name = "marksold"),
    path("about-us", views.about_us, name='about_us'),
    path("categories", views.categories, name='categories'),
    path("repost/<int:id>", views.repost, name="repost"),
    path("bulk-action/<str:action>/", views.bulk_action, name="bulk_action"),
    path("log-install/", views.log_install, name="log_install"),
    path("terms", views.terms, name='terms'),
    path("bypass", views.bypass, name='bypass'),
    path('analytics/', views.analytics, name='analytics'),
    path('save-subscription/', views.save_subscription, name='save_subscription'),
    path('unsubscribe/<str:token>/', views.unsubscribe_view, name='unsubscribe'),
    path('api/items/', views.api_items, name='api_items'),
    path('api/item/<int:id>', views.api_items_post, name = 'post/put api items'),
    path('api/item/', views.api_items_post, name = "only post"),
    path('api/items/<int:id>/', views.api_items, name='api_items_detail'),
    path('api/<int:id>/images', views.api_item_images, name='items-images'),
    path('api/updatestats/<int:id>', views.api_update_item, name = "change sold status"),
    path('api/feedback', views.api_feedback, name = "api feedback"),
    path('api/categories/', views.api_cats, name = "api categories"),
    path('api/hostels/', views.api_hstls, name = "api hostels"),
    path('api/repost/', views.api_repost, name = "api reposts"),
    path('api/csrf/', views.get_csrf_token),
    # path('api/additem', views.api_item, name = "add item"),
    path("bp-bot/", views.bp_bot_webhook, name="bp_bot_webhook"),
]
