# Generated by Django 5.1.6 on 2025-04-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0009_remove_item_product_name_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='campus',
            field=models.CharField(choices=[('GOA', 'Goa'), ('HYD', 'Hyderabad'), ('PIL', 'Pilani'), ('OTH', 'Others'), ('GMAIL', 'Gmail')], default='GOA', max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='campus',
            field=models.CharField(choices=[('GOA', 'Goa'), ('HYD', 'Hyderabad'), ('PIL', 'Pilani'), ('OTH', 'Others'), ('GMAIL', 'Gmail')], max_length=5),
        ),
    ]
