# Generated by Django 5.1.7 on 2025-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0011_alter_hostel_campus_alter_person_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='campus',
            field=models.CharField(choices=[('GOA', 'Goa'), ('HYD', 'Hyderabad'), ('PIL', 'Pilani'), ('OTH', 'Others'), ('GMAIL', 'Gmail')], default='GOA', max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='campus',
            field=models.CharField(choices=[('GOA', 'Goa'), ('HYD', 'Hyderabad'), ('PIL', 'Pilani'), ('OTH', 'Others'), ('GMAIL', 'Gmail')], max_length=5),
        ),
    ]
