# Generated by Django 5.1.7 on 2025-04-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0011_alter_hostel_name'),
        ('bits', '0012_alter_hostel_campus_alter_person_campus'),
    ]

    operations = [
    ]
