# Generated by Django 5.1.7 on 2025-04-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0017_pagevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
