# Generated by Django 5.1.7 on 2025-04-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0018_delete_pagevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='campus',
            field=models.CharField(choices=[('GOA', 'Goa'), ('HYD', 'Hyderabad'), ('PIL', 'Pilani'), ('DUB', 'Dubai'), ('OTH', 'Others'), ('GMAIL', 'Gmail')], default='GOA', max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='campus',
            field=models.CharField(choices=[('GOA', 'Goa'), ('HYD', 'Hyderabad'), ('PIL', 'Pilani'), ('DUB', 'Dubai'), ('OTH', 'Others'), ('GMAIL', 'Gmail')], max_length=5),
        ),
    ]
