# Generated by Django 5.1.7 on 2025-04-27 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0019_alter_hostel_campus_alter_person_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_notification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
