# Generated by Django 5.1.7 on 2025-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0020_person_last_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
