# Generated by Django 5.1.7 on 2025-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0021_category_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
