# Generated by Django 5.1.7 on 2025-05-01 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0022_person_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='bits.person'),
        ),
    ]
