# Generated by Django 5.2.4 on 2025-07-11 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0023_alter_feedback_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bits.hostel'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['item', 'display_order'], name='bits_image_item_id_2aab9c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_sold', '-updated_at'], name='item_sold_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_sold', 'price'], name='item_sold_price_asc_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_sold', '-price'], name='item_sold_price_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['seller', 'is_sold', '-updated_at'], name='item_seller_sold_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_sold', '-updated_at'], name='item_cat_sold_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='item_name_idx'),
        ),
    ]
